---
- name: Ansible playbook
  hosts: localhost
  become: yes
  tasks:
    - name: Install OpenSSH package
      pacman:
        name: openssh
        state: present
      register: ssh_install
    - name: Log OpenSSH installation status
      debug:
        msg: "OpenSSH package installed: {{ ssh_install.changed }}"

    - name: Enable SSH service to start on boot
      systemd:
        name: sshd
        enabled: yes
        state: started
      register: ssh_enable
    - name: Log SSH service enable status
      debug:
        msg: "SSH service enabled and started: {{ ssh_enable.changed }}"

    - name: Install ttf-meslo-nerd font
      pacman:
        name: ttf-meslo-nerd
        state: present
      register: font_install
    - name: Log font installation status
      debug:
        msg: "Font installed: {{ font_install.changed }}"

    - name: Install fastfetch package using yay
      become: no
      command: yay -S --noconfirm fastfetch
      register: fastfetch_install
    - name: Log fastfetch installation status
      debug:
        msg: "Fastfetch installed: {{ fastfetch_install.changed }}"

    - name: Install feh package using yay
      become: no
      command: yay -S --noconfirm feh
      register: feh_install
    - name: Log feh installation status
      debug:
        msg: "Feh installed: {{ feh_install.changed }}"

    - name: Install fzf package using yay
      become: no
      command: yay -S --noconfirm fzf
      register: fzf_install
    - name: Log fzf installation status
      debug:
        msg: "Fzf installed: {{ fzf_install.changed }}"

    - name: Install i3 package using yay
      become: no
      command: yay -S --noconfirm i3
      register: i3_install
    - name: Log i3 installation status
      debug:
        msg: "i3 installed: {{ i3_install.changed }}"

    - name: Install kitty package using yay
      become: no
      command: yay -S --noconfirm kitty
      register: kitty_install
    - name: Log kitty installation status
      debug:
        msg: "Kitty installed: {{ kitty_install.changed }}"

    - name: Install maim package using yay
      become: no
      command: yay -S --noconfirm maim
      register: maim_install
    - name: Log maim installation status
      debug:
        msg: "Maim installed: {{ maim_install.changed }}"

    - name: Install neovim package using yay
      become: no
      command: yay -S --noconfirm neovim
      register: neovim_install
    - name: Log neovim installation status
      debug:
        msg: "Neovim installed: {{ neovim_install.changed }}"

    - name: Install picom package using yay
      become: no
      command: yay -S --noconfirm picom
      register: picom_install
    - name: Log picom installation status
      debug:
        msg: "Picom installed: {{ picom_install.changed }}"

    - name: Install polybar package using yay
      become: no
      command: yay -S --noconfirm polybar
      register: polybar_install
    - name: Log polybar installation status
      debug:
        msg: "Polybar installed: {{ polybar_install.changed }}"

    - name: Install rofi package using yay
      become: no
      command: yay -S --noconfirm rofi
      register: rofi_install
    - name: Log rofi installation status
      debug:
        msg: "Rofi installed: {{ rofi_install.changed }}"

    - name: Install tmux package using yay
      become: no
      command: yay -S --noconfirm tmux
      register: tmux_install
    - name: Log tmux installation status
      debug:
        msg: "Tmux installed: {{ tmux_install.changed }}"

    - name: Install xorg-xrdb package using yay
      become: no
      command: yay -S --noconfirm xorg-xrdb
      register: xorg_xrdb_install
    - name: Log xorg-xrdb installation status
      debug:
        msg: "Xorg-xrdb installed: {{ xorg_xrdb_install.changed }}"

    - name: Install xclip package using yay
      become: no
      command: yay -S --noconfirm xclip
      register: xclip_install
    - name: Log xclip installation status
      debug:
        msg: "Xclip installed: {{ xclip_install.changed }}"

    - name: Install zsh package using yay
      become: no
      command: yay -S --noconfirm zsh
      register: zsh_install
    - name: Log zsh installation status
      debug:
        msg: "Zsh installed: {{ zsh_install.changed }}"

    - name: Install zsh-theme-powerlevel10k-git package using yay
      become: no
      shell: |
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
        echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc
      args:
        creates: ~/powerlevel10k
      register: powerlevel10k_install
    - name: Log zsh-theme-powerlevel10k-git installation status
      debug:
        msg: "Powerlevel10k installed: {{ powerlevel10k_install.changed }}"

    - name: Install xrdp package using yay
      become: no
      command: yay -S --noconfirm xrdp
      register: xrdp_install
    - name: Log xrdp installation status
      debug:
        msg: "XRDP installed: {{ xrdp_install.changed }}"

    - name: Install xorgxrdp package using yay
      become: no
      command: yay -S --noconfirm xorgxrdp
      register: xorgxrdp_install
    - name: Log xorgxrdp installation status
      debug:
        msg: "Xorgxrdp installed: {{ xorgxrdp_install.changed }}"

    - name: Install qt6-base package using yay
      become: no
      command: yay -S --noconfirm qt6-base
      register: qt6_base_install
    - name: Log qt6-base installation status
      debug:
        msg: "Qt6 base installed: {{ qt6_base_install.changed }}"

    - name: Install qt5-base package using yay
      become: no
      command: yay -S --noconfirm qt5-base
      register: qt5_base_install
    - name: Log qt5-base installation status
      debug:
        msg: "Qt5 base installed: {{ qt5_base_install.changed }}"

    - name: Install gtk4 package using yay
      become: no
      command: yay -S --noconfirm gtk4
      register: gtk4_install
    - name: Log gtk4 installation status
      debug:
        msg: "Gtk4 installed: {{ gtk4_install.changed }}"

    - name: Install gtk3 package using yay
      become: no
      command: yay -S --noconfirm gtk3
      register: gtk3_install
    - name: Log gtk3 installation status
      debug:
        msg: "Gtk3 installed: {{ gtk3_install.changed }}"

    - name: Install gnome-themes-extra package using yay
      become: no
      command: yay -S --noconfirm gnome-themes-extra
      register: gnome_themes_install
    - name: Log gnome-themes-extra installation status
      debug:
        msg: "Gnome themes installed: {{ gnome_themes_install.changed }}"

    - name: Install adwaita-qt5-git package using yay
      become: no
      command: yay -S --noconfirm adwaita-qt5-git
      register: adwaita_qt5_install
    - name: Log adwaita-qt5-git installation status
      debug:
        msg: "Adwaita-qt5-git installed: {{ adwaita_qt5_install.changed }}"

    - name: Install adwaita-qt6-git package using yay
      become: no
      command: yay -S --noconfirm adwaita-qt6-git
      register: adwaita_qt6_install
    - name: Log adwaita-qt6-git installation status
      debug:
        msg: "Adwaita-qt6-git installed: {{ adwaita_qt6_install.changed }}"

    - name: Install pipewire-module-xrdp package using yay
      become: no
      command: yay -S --noconfirm pipewire-module-xrdp
      register: pipewire_xrdp_install
    - name: Log pipewire-module-xrdp installation status
      debug:
        msg: "Pipewire module for XRDP installed: {{ pipewire_xrdp_install.changed }}"

    - name: Install mesa package using pacman
      pacman:
        name: mesa
        state: present
      register: mesa_install
    - name: Log mesa installation status
      debug:
        msg: "Mesa installed: {{ mesa_install.changed }}"

    - name: Install vulkan-radeon package using pacman
      pacman:
        name: vulkan-radeon
        state: present
      register: vulkan_install
    - name: Log vulkan installation status
      debug:
        msg: "Vulkan installed: {{ vulkan_install.changed }}"

    - name: Install libva-mesa-driver package using pacman
      pacman:
        name: libva-mesa-driver
        state: present
      register: libva_mesa_install
    - name: Log libva-mesa-driver installation status
      debug:
        msg: "Libva-mesa-driver installed: {{ libva_mesa_install.changed }}"

    - name: Install libva-utils package using pacman
      pacman:
        name: libva-utils
        state: present
      register: libva_utils_install
    - name: Log libva-utils installation status
      debug:
        msg: "Libva-utils installed: {{ libva_utils_install.changed }}"

    - name: Install xorg package using pacman
      pacman:
        name: xorg
        state: present
      register: xorg_install
    - name: Log xorg installation status
      debug:
        msg: "Xorg installed: {{ xorg_install.changed }}"

    - name: Install xorg-server package using pacman
      pacman:
        name: xorg-server
        state: present
      register: xorg_server_install
    - name: Log xorg-server installation status
      debug:
        msg: "Xorg-server installed: {{ xorg_server_install.changed }}"

    - name: Install xorg-xinit package using pacman
      pacman:
        name: xorg-xinit
        state: present
      register: xorg_xinit_install
    - name: Log xorg-xinit installation status
      debug:
        msg: "Xorg-xinit installed: {{ xorg_xinit_install.changed }}"

    - name: Enable xrdp service to start on boot
      systemd:
        name: xrdp
        enabled: yes
        state: started
      register: xrdp_enable
    - name: Log xrdp service enable status
      debug:
        msg: "xrdp service enabled and started: {{ xrdp_enable.changed }}"

    - name: Ensure the tmux plugins directory exists with proper permissions
      become: yes
      file:
        path: "{{ ansible_env.HOME }}/.tmux/plugins"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    - name: Install tmux plugin manager (TPM) using shell with if check
      become: no
      shell: |
        if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
          git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
        fi
      register: tmux_plugin_manager
    - name: Log tmux plugin manager installation status
      debug:
        msg: "Tmux plugin manager installed: {{ tmux_plugin_manager.changed }}"

    - name: Install Oh My Zsh using shell if .oh-my-zsh does not exist
      become: no
      shell: >
        if [ ! -d "{{ ansible_env.HOME }}/.oh-my-zsh" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi
      args:
        creates: "~/.oh-my-zsh"
      register: ohmyzsh_install

    - name: Install zsh-autosuggestions plugin using shell with if check
      become: no
      shell: |
        if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
          git clone https://github.com/zsh-users/zsh-autosuggestions "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        fi
      register: zsh_autosuggestions

    - name: Log zsh-autosuggestions installation status
      debug:
        msg: "zsh-autosuggestions plugin installed: {{ zsh_autosuggestions.changed }}"

    - name: Install zsh-completions plugin using shell with if check
      become: no
      shell: |
        if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-completions" ]; then
          git clone https://github.com/zsh-users/zsh-completions "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"
        fi
      register: zsh_completions

    - name: Log zsh-completions installation status
      debug:
        msg: "zsh-completions plugin installed: {{ zsh_completions.changed }}"

    - name: Install zsh-syntax-highlighting plugin using shell with if check
      become: no
      shell: |
        if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
          git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        fi
      register: zsh_syntax_highlighting

    - name: Log zsh-syntax-highlighting installation status
      debug:
        msg: "zsh-syntax-highlighting plugin installed: {{ zsh_syntax_highlighting.changed }}"

    - name: Install stow using yay
      become: no
      command: yay -Sy --noconfirm stow
      register: stow_install
    - name: Log stow installation status
      debug:
        msg: "Stow installed: {{ stow_install.changed }}"

    - name: Remove .xinitrc file using shell
      become: no
      shell: |
        rm -f .xinitrc
      ignore_errors: yes

    - name: Remove .zshrc file using shell
      become: no
      shell: |
        rm -f .zshrc
      ignore_errors: yes

    - name: Recursively run stow on ~/dotfiles
      become: no
      shell: |
        cd ~/dotfiles && \
        rm -rf aerospace && \
        for file in *; do
          stow "$file"
        done
      register: stow_run
    - name: Log stow run status
      debug:
        msg: "Dotfiles stowed: {{ stow_run.changed }}"

    - name: Change default shell to zsh for user
      shell: |
        if [ -x /bin/zsh ]; then
            chsh -s /bin/zsh
        elif [ -x /usr/bin/zsh ]; then
            chsh -s /usr/bin/zsh
        else
            echo "zsh not found in expected locations."
        fi
      register: change_shell

    - name: Debug output of the change shell task
      debug:
        var: change_shell
