---
- name: Ansible playbook
  hosts: localhost
  become: yes
  tasks:
    - name: Install OpenSSH package
      pacman:
        name: openssh
        state: present
      register: ssh_install
    - name: Log OpenSSH installation status
      debug:
        msg: "OpenSSH package installed: {{ ssh_install.changed }}"

    - name: Enable SSH service to start on boot
      systemd:
        name: sshd
        enabled: yes
        state: started
      register: ssh_enable
    - name: Log SSH service enable status
      debug:
        msg: "SSH service enabled and started: {{ ssh_enable.changed }}"

    - name: Install fonts
      pacman:
        name: ttf-meslo-nerd
        state: present
      register: font_install
    - name: Log font installation status
      debug:
        msg: "Fonts installed: {{ font_install.changed }}"

    # Split yay installations
    - name: Install fastfetch using yay
      become: no
      command: yay -Sy --noconfirm fastfetch
      register: fastfetch_install
    - name: Log fastfetch installation status
      debug:
        msg: "fastfetch installed: {{ fastfetch_install.changed }}"

    - name: Install feh using yay
      become: no
      command: yay -Sy --noconfirm feh
      register: feh_install
    - name: Log feh installation status
      debug:
        msg: "feh installed: {{ feh_install.changed }}"

    - name: Install fzf using yay
      become: no
      command: yay -Sy --noconfirm fzf
      register: fzf_install
    - name: Log fzf installation status
      debug:
        msg: "fzf installed: {{ fzf_install.changed }}"

    - name: Install i3 using yay
      become: no
      command: yay -Sy --noconfirm i3
      register: i3_install
    - name: Log i3 installation status
      debug:
        msg: "i3 installed: {{ i3_install.changed }}"

    - name: Install kitty using yay
      become: no
      command: yay -Sy --noconfirm kitty
      register: kitty_install
    - name: Log kitty installation status
      debug:
        msg: "kitty installed: {{ kitty_install.changed }}"

    - name: Install maim using yay
      become: no
      command: yay -Sy --noconfirm maim
      register: maim_install
    - name: Log maim installation status
      debug:
        msg: "maim installed: {{ maim_install.changed }}"

    - name: Install neovim using yay
      become: no
      command: yay -Sy --noconfirm neovim
      register: neovim_install
    - name: Log neovim installation status
      debug:
        msg: "neovim installed: {{ neovim_install.changed }}"

    - name: Install picom using yay
      become: no
      command: yay -Sy --noconfirm picom
      register: picom_install
    - name: Log picom installation status
      debug:
        msg: "picom installed: {{ picom_install.changed }}"

    - name: Install polybar using yay
      become: no
      command: yay -Sy --noconfirm polybar
      register: polybar_install
    - name: Log polybar installation status
      debug:
        msg: "polybar installed: {{ polybar_install.changed }}"

    - name: Install rofi using yay
      become: no
      command: yay -Sy --noconfirm rofi
      register: rofi_install
    - name: Log rofi installation status
      debug:
        msg: "rofi installed: {{ rofi_install.changed }}"

    - name: Install tmux using yay
      become: no
      command: yay -Sy --noconfirm tmux
      register: tmux_install
    - name: Log tmux installation status
      debug:
        msg: "tmux installed: {{ tmux_install.changed }}"

    - name: Install xorg-xrdb using yay
      become: no
      command: yay -Sy --noconfirm xorg-xrdb
      register: xorg_xrdb_install
    - name: Log xorg-xrdb installation status
      debug:
        msg: "xorg-xrdb installed: {{ xorg_xrdb_install.changed }}"

    - name: Install xclip using yay
      become: no
      command: yay -Sy --noconfirm xclip
      register: xclip_install
    - name: Log xclip installation status
      debug:
        msg: "xclip installed: {{ xclip_install.changed }}"

    - name: Install zsh using yay
      become: no
      command: yay -Sy --noconfirm zsh
      register: zsh_install
    - name: Log zsh installation status
      debug:
        msg: "zsh installed: {{ zsh_install.changed }}"

    - name: Install zsh-theme-powerlevel10k-git using yay
      become: no
      shell: |
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
        echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc
      args:
        creates: ~/powerlevel10k
      register: zsh_powerlevel10k_install
    - name: Log zsh-theme-powerlevel10k-git installation status
      debug:
        msg: "zsh-theme-powerlevel10k-git installed: {{ zsh_powerlevel10k_install.changed }}"
      
    - name: Install xrdp using yay
      become: no
      command: yay -S --noconfirm xrdp
      register: xrdp_install
    - name: Log xrdp installation status
      debug:
        msg: "xrdp installed: {{ xrdp_install.changed }}"

    - name: Enable xrdp service to start on boot
      systemd:
        name: xrdp
        enabled: yes
        state: started
      register: xrdp_enable
    - name: Log xrdp service enable status
      debug:
        msg: "xrdp service enabled and started: {{ xrdp_enable.changed }}"

    - name: Install xorgxrdp using yay
      become: no
      command: yay -S --noconfirm xorgxrdp
      register: xorgxrdp_install
    - name: Log xorgxrdp installation status
      debug:
        msg: "xorgxrdp installed: {{ xorgxrdp_install.changed }}"

    - name: Install xorg using yay
      pacman:
        name: xorg
        state: present
      register: xorg_install
    - name: Log xorg installation status
      debug:
        msg: "xorg installed: {{ xorg_install.changed }}"

    - name: Install xorg-server using yay
      pacman:
        name: xorg-server
        state: present
      register: xorg_server_install
    - name: Log xorg-server installation status
      debug:
        msg: "xorg-server installed: {{ xorg_server_install.changed }}"

    - name: Install xorg-xinit using yay
      pacman:
        name: xorg-xinit
        state: present
      register: xorg_xinit_install
    - name: Log xorg-xinit installation status
      debug:
        msg: "xorg-xinit installed: {{ xorg_xinit_install.changed }}"

    - name: Install pipewire-module-xrdp using yay
      become: no
      command: yay -S --noconfirm pipewire-module-xrdp
      register: pipewire_module_xrdp_install
    - name: Log pipewire-module-xrdp installation status
      debug:
        msg: "pipewire-module-xrdp installed: {{ pipewire_module_xrdp_install.changed }}"

    - name: Install qt6-base using yay
      become: no
      command: yay -Sy --noconfirm qt6-base
      register: qt6_base_install
    - name: Log qt6-base installation status
      debug:
        msg: "qt6-base installed: {{ qt6_base_install.changed }}"

    - name: Install qt5-base using yay
      become: no
      command: yay -Sy --noconfirm qt5-base
      register: qt5_base_install
    - name: Log qt5-base installation status
      debug:
        msg: "qt5-base installed: {{ qt5_base_install.changed }}"

    - name: Install gtk4 using yay
      become: no
      command: yay -Sy --noconfirm gtk4
      register: gtk4_install
    - name: Log gtk4 installation status
      debug:
        msg: "gtk4 installed: {{ gtk4_install.changed }}"

    - name: Install gtk3 using yay
      become: no
      command: yay -Sy --noconfirm gtk3
      register: gtk3_install
    - name: Log gtk3 installation status
      debug:
        msg: "gtk3 installed: {{ gtk3_install.changed }}"

    - name: Install gnome-themes-extra using yay
      become: no
      command: yay -Sy --noconfirm gnome-themes-extra
      register: gnome_themes_extra_install
    - name: Log gnome-themes-extra installation status
      debug:
        msg: "gnome-themes-extra installed: {{ gnome_themes_extra_install.changed }}"

    - name: Install adwaita-qt5-git using yay
      become: no
      command: yay -Sy --noconfirm adwaita-qt5-git
      register: adwaita_qt5_install
    - name: Log adwaita-qt5-git installation status
      debug:
        msg: "adwaita-qt5-git installed: {{ adwaita_qt5_install.changed }}"

    - name: Install adwaita-qt6-git using yay
      become: no
      command: yay -Sy --noconfirm adwaita-qt6-git
      register: adwaita_qt6_install
    - name: Log adwaita-qt6-git installation status
      debug:
        msg: "adwaita-qt6-git installed: {{ adwaita_qt6_install.changed }}"
